on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron:  '0 0 * * 0'

name: Render Badges

jobs:
  render:
    name: Render Badges
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install rmarkdown, remotes, and the local package
        run: |
          install.packages("remotes")
          remotes::install_cran("httr")
        shell: Rscript {0}

      - name: Render badges
        run: |
          setwd("badges/")
          source("badges.R")
        shell: Rscript {0}

      - name: Commit rendered badges
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add badges/\*
          git commit -m "Re-build badges on `date +'%Y-%m-%d %H:%M:%S'`" || echo "No changes to commit"
          git push origin master || echo "No changes to commit"

